#!/bin/bash
#-------------------------------------------------------------------------------
# Description: Lite Tweaks - Set a default Browser
# This script must be run with elevated privileges (gksudo)
# Authors: Misko_2083, Jerry Bezencon
# Website: https://www.linuxliteos.com
#-------------------------------------------------------------------------------

test_1=(`cat "/etc/gnome/defaults.list" | grep "application/xhtml+xml"`)
test_2=(`cat "/etc/gnome/defaults.list" | grep "text/html"`)
test_3=(`cat "/etc/gnome/defaults.list" | grep "x-scheme-handler/http"`)
test_4=(`cat "/etc/gnome/defaults.list" | grep "x-scheme-handler/https"`)

if [ "${test_1[0]}" = "application/xhtml+xml=firefox.desktop;" ] && [ "${test_2[0]}" = "text/html=firefox.desktop;" ] && [ "${test_3[0]}" = "x-scheme-handler/http=firefox.desktop;" ] && [ "${test_4[0]}" = "x-scheme-handler/https=firefox.desktop;" ]; then
	firefox=("TRUE" "Firefox" "default" "Firefox is currently your default web browser" )
	googlechrome=("FALSE" "Google Chrome" "not default" "Set Google Chrome as default web browser" )
	chromium=("FALSE" "Chromium" "not default" "Set Google Chrome as default web browser" )
	midori=("FALSE" "Midori" "not default" "Set Midori as the default web browser" )
elif [ "${test_1[0]}" = "application/xhtml+xml=chromium-browser.desktop;firefox.desktop;" ] && [ "${test_2[0]}" = "text/html=chromium-browser.desktop;firefox.desktop;" ] && [ "${test_3[0]}" = "x-scheme-handler/http=chromium-browser.desktop;firefox.desktop;" ] && [ "${test_4[0]}" = "x-scheme-handler/https=chromium-browser.desktop;firefox.desktop;" ]; then
	firefox=("FALSE" "Firefox" "not default" "Set firefox as the default web browser" )
	googlechrome=("FALSE" "Google Chrome" "not default" "Set Google Chrome as default web browser" )
	chromium=("TRUE" "Chromium" "default" "Chromium is currently your default web browser" )
	midori=("FALSE" "Midori" "not default" "Set Midori as the default web browser" )
elif [ "${test_1[0]}" = "application/xhtml+xml=midori.desktop;firefox.desktop;" ] && [ "${test_2[0]}" = "text/html=midori.desktop;firefox.desktop;" ] && [ "${test_3[0]}" = "x-scheme-handler/http=midori.desktop;firefox.desktop;" ] && [ "${test_4[0]}" = "x-scheme-handler/https=midori.desktop;firefox.desktop;" ]; then
	firefox=("FALSE" "Firefox" "not default" "Set firefox as the default web browser" )
	googlechrome=("FALSE" "Google Chrome" "not default" "Set Google Chrome as default web browser" )
	chromium=("FALSE" "Chromium" "not default" "Set Chromium as default web browser" )
	midori=("TRUE" "Midori" "default" "Midori is currently your default web browser" )
else
	firefox=("FALSE" "Firefox" "not default" "Set firefox as the default web browser" )
	googlechrome=("TRUE" "Google Chrome" "default" "Google Chrome is currently your default web browser" )
	chromium=("FALSE" "Chromium" "not default" "Set Chromium as the default web browser" )
	midori=("FALSE" "Midori" "not default" "Set Midori as the default web browser" )
fi

ic="/usr/share/icons/zenity-llcc.png"

selection=$(zenity --window-icon="$ic" --list --radiolist --width=650 --height=240 --column="Select" --column="Name" --column="Status" \
--column="Description" --text="Select the web browser you wish to set as default." --title="Choose a default browser" --ok-label="Set" --cancel-label="Quit" \
"${firefox[@]}" "${googlechrome[@]}" "${chromium[@]}" "${midori[@]}")

case "$selection" in
"Firefox") `sudo sed -i "s!^"${test_1[0]}"!application/xhtml+xml=firefox.desktop;!g" /etc/gnome/defaults.list `;
		`sudo sed -i "s!^"${test_2[0]}"!text/html=firefox.desktop;!g" /etc/gnome/defaults.list `; \
		`sudo sed -i "s!^"${test_3[0]}"!x-scheme-handler/http=firefox.desktop;!g" /etc/gnome/defaults.list `; \
		`sudo sed -i "s!^"${test_4[0]}"!x-scheme-handler/https=firefox.desktop;!g" /etc/gnome/defaults.list `;;
"Google Chrome") `sudo sed -i "s!^"${test_1[0]}"!application/xhtml+xml=google-chrome.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `; \
		`sudo sed -i "s!^"${test_2[0]}"!text/html=google-chrome.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `; \
		`sudo sed -i "s!^"${test_3[0]}"!x-scheme-handler/http=google-chrome.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `; \
		`sudo sed -i "s!^"${test_4[0]}"!x-scheme-handler/https=google-chrome.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `;;
"Chromium") `sudo sed -i "s!^"${test_1[0]}"!application/xhtml+xml=chromium-browser.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `; \
		`sudo sed -i "s!^"${test_2[0]}"!text/html=chromium-browser.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `; \
		`sudo sed -i "s!^"${test_3[0]}"!x-scheme-handler/http=chromium-browser.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `; \
		`sudo sed -i "s!^"${test_4[0]}"!x-scheme-handler/https=chromium-browser.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `;;
"Midori") `sudo sed -i "s!^"${test_1[0]}"!application/xhtml+xml=midori.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `; \
		`sudo sed -i "s!^"${test_2[0]}"!text/html=midori.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `; \
		`sudo sed -i "s!^"${test_3[0]}"!x-scheme-handler/http=midori.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `; \
		`sudo sed -i "s!^"${test_4[0]}"!x-scheme-handler/https=midori.desktop;firefox.desktop;!g" /etc/gnome/defaults.list `;;
esac
